name: Build WLED

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install ESP-IDF
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh

    - name: Source ESP-IDF environment
      run: |
        cd esp-idf
        . ./export.sh
      shell: bash

    - name: Prepare WLED build
      run: |
        cd $GITHUB_WORKSPACE
        git submodule update --init --recursive
        mkdir -p build
        cp platformio_override.ini.example platformio_override.ini
        echo "build_unflags = -fno-rtti" >> platformio_override.ini
        echo "build_flags = -DRTC_USER_DATA_ENABLE" >> platformio_override.ini

    - name: Build WLED firmware
      run: |
        cd $GITHUB_WORKSPACE
        cd esp-idf
        . ./export.sh
        cd $GITHUB_WORKSPACE
        idf.py build
      shell: bash

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: wled-firmware
        path: |
          $GITHUB_WORKSPACE/build/*.bin

